#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S2,     IR_sensor,      sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     colorSensor,    sensorLightActive)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_Matrix_S1_1, motorRight,    tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motorLeft,     tmotorMatrix, openLoop, reversed)
#pragma config(Motor,  mtr_Matrix_S1_3, motorF,        tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		if (SensorValue[colorSensor] < 40)
		{
			motor[motorLeft]= 20;
			motor[motorRight]= 5;
		}
		else if(SensorValue[colorSensor]>40)
		{
			motor[motorLeft]= 20;
			motor[motorRight]= 10;
		}
	}

}
