#pragma config(Sensor, S1,     ,               sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-------------------------------------------------------------IR-Sensor----------------------------------------------------------------------------------------*/

void function moveUntil(string sensorLeft,string sensorRight,string motorLeft,string motorRight,int thresholdLeft,int thresholdRight, int mpowerLeft, int mpowerRight)
{


}
