#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     GYRO,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     scoreWrist,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     carWash,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     liftArm,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     scoreArm,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     pullUp,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     flagSpinner,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    autoServo,            tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Controls list
Joy 1 sticks = driving

*/
#include "helpers_test.h"
#include "configuration_test.h"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v2.h"


const tMUXSensor irsensor1 = msensor_S4_2;
const tMUXSensor topTouch = msensor_S4_1;
const tMUXSensor bottomTouch = msensor_S4_3;
const tMUXSensor irsensor2 = msensor_S4_4;

int timeinterface ()
{
	int yourtime = 0;

	ClearTimer(T1);

	until(nNxtButtonPressed == 3 || time1[T1]>WAIT_MENU_TIMEOUT)
	{
		eraseDisplay();
		nxtDisplayBigTextLine(3, "Wait?");
		nxtDisplayBigTextLine(5, "-> %d", yourtime);

		if(nNxtButtonPressed == 2)
		{
			yourtime -= 5;
			wait1Msec(400);
		}
		if(nNxtButtonPressed == 1)
		{
			yourtime += 5;
			wait1Msec(400);
		}

	}
	return yourtime;
}

task heading()
{
	float delTime = 0.0;
	float prevHeading = 0.0;
	float curRate = 0.0;
	HTGYROstartCal(GYRO);
   while (true) {
   	time1[T1] = 0;
    	curRate = HTGYROreadRot(GYRO);
    	if (abs(curRate) > 3) {
      	prevHeading = currHeading;
      	currHeading = prevHeading + (curRate * delTime);
      	if (currHeading > 360) currHeading -= 360;
      	else if (currHeading < 0) currHeading += 360;
    		}
    nxtDisplayTextLine(4, "Curr = %f", currHeading);
   	wait1Msec(5);
    	delTime = ((float)time1[T1]) / 1000;
    	//delTime /= 1000;
	}

}

int count =  0;
int direction = -1;

void initializeRobot()
{
	if (!MUXtest())
	{
		PlayTone(1200,500);
	}


	// Initialize encoders
  resetEncoders();

	// Spawn heading tracking thread
	StartTask(heading);
  wait1Msec(1000);

  return;
}

	task main()
{

	bool blockDropped = false;


while(blockDropped == false)
{
	while ( nMotorEncoder[RightDrive] < doubleIRthreshold)
		{
			if(check12(irsensor1 , irsensor2) == true && blockDropped == false)
			{
				halt();
				wait1Msec(10);
				servoTarget[autoServo] = AUTO_SCORING_ARM_DEPLOY_DISTANCE;
				wait1Msec(WAIT_BEFORE_RETRACT_AUTO_SCORE_ARM_MS);
				servoTarget[autoServo] = 255;
				wait1Msec(500);

				blockDropped = true;
			}

			else
			{
				moveForward();
			}

		}

	while (!check34(irsensor1 , irsensor2)  && nMotorEncoder[RightDrive] > doubleIRthreshold)
		{
			while ( nMotorEncoder[RightDrive] < doubleIRthreshold)
		{
			if(check34(irsensor1 , irsensor2) == true && blockDropped == false)
			{
				halt();
				wait1Msec(10);
				servoTarget[autoServo] = AUTO_SCORING_ARM_DEPLOY_DISTANCE;
				wait1Msec(WAIT_BEFORE_RETRACT_AUTO_SCORE_ARM_MS);
				servoTarget[autoServo] = 255;
				wait1Msec(500);

				blockDropped = true;
			}

			else
			{
				moveForward();
			}
		}

	}

}


}
