#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S3,     HTSMUX,              sensorI2CCustom)
#pragma config(Motor,  mtr_S2_C1_1,     ArmMotor,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     empty,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     LeftDrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     RightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C3_1,     Scissor,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    RightWrist,           tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "drivers/hitechnic-sensormux.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"
#include "drivers/lego-touch.h"

const tMUXSensor irsensor1 = msensor_S3_3;
const tMUXSensor irsensor2 = msensor_S3_4;
const tMUXSensor upTouch = msensor_S3_1;
const tMUXSensor downTouch = msensor_S3_2;



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.


  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();


  int speed_divisor = 0;
  int thresholdP = 10; //dead zone thresholds
  int thresholdN = -10; //dead zone thresholds
  int wristPos = ServoValue[Wrist];
  int rightWristPos = ServoValue[RightWrist];
	int allUp = false;
	int allDown = false;

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {

  getJoystickSettings(joystick);


  //This is the driving code.  Two stick steering
  //The old speed divisor variable should set us to full speed
  if (joy1Btn(5)== 1){
  	speed_divisor = 200;
	}else{
  	speed_divisor = 300;
  }

  if (abs(joystick.joy1_y1) < 10 & abs(joystick.joy1_x2) < 10) {
      motor[LeftDrive] = 0;
     motor[RightDrive] = 0;

  } else {
       motor[LeftDrive] = (- joystick.joy1_y1 + joystick.joy1_x2) * 100 / speed_divisor;
       motor[RightDrive] = (- joystick.joy1_y1 - joystick.joy1_x2) * 100 / speed_divisor;
  }


  //Arm motor movement
  if((joystick.joy2_y1) > thresholdP)
    {
     //motor[ArmMotor] = ( ( (joystick.joy2_y1) * (joystick.joy2_y1) ) / 161.29) / 15; //squared control with speed max of 20
     //wait10Msec(5);
     motor[ArmMotor] = joystick.joy2_y1/3;
     nxtDisplayTextLine(7, "%d", nMotorEncoder[ArmMotor]);
    }

   if((joystick.joy2_y1) < thresholdN)
    {
     //motor[ArmMotor] = -( ( (joystick.joy2_y1) * (joystick.joy2_y1)) / 161.29) / 15; //squared control with speed max of 20
     //wait10Msec(5);
     motor[ArmMotor] = joystick.joy2_y1/3;
     nxtDisplayTextLine(7, "%d", nMotorEncoder[ArmMotor]);
    }

   if((joystick.joy2_y1) < thresholdP && (joystick.joy2_y1) > thresholdN)
    {
     motor[ArmMotor] = 0;



     //wait1Msec(50);
    }


   //Arm wrist movement
   if((joystick.joy2_y2) > thresholdP)
    {

     wristPos = ServoValue[Wrist];
		 rightWristPos = ServoValue[RightWrist];


     wristPos = wristPos+1;
     rightWristPos = rightWristPos-1;
     if (wristPos>255){
       wristPos = 255;
     }
     if (rightWristPos<0){
       rightWristPos = 0;
     }

     servoTarget[Wrist] = wristPos;
     servoTarget[RightWrist] = rightWristPos;

     wait1Msec(5);
    }

   if((joystick.joy2_y2) < thresholdN)
    {

     wristPos = ServoValue[Wrist];
     rightWristPos = ServoValue[RightWrist];

     wristPos = wristPos-1;
     rightWristPos = rightWristPos+1;
     if (wristPos<0){
       wristPos = 0;
     }

     if (rightWristPos>255){
       rightWristPos = 255;
     }
     servoTarget[Wrist] = wristPos;
     servoTarget[RightWrist] = rightWristPos;
     wait1Msec(5);

    }





  //Scissor Lift  button 2 to go up, button 4 to go down - 3 should make it go all the way up.
  	if (joy2Btn(1)==1){
  		allUp = true;
  		allDown = false;
  	}

  	if (TSreadState(upTouch) == true){
  		allUp = false;

    }

  	if (allUp == true && TSreadState(upTouch) != true){
  		motor[Scissor] = 100;

  	}
		if (joy2Btn(3)==1){
  		allDown = true;
  		allUp = false;
  	}

  	if (TSreadState(downTouch) == true){
  		allDown = false;
    }

  	if (allDown == true && TSreadState(downTouch) != true){
  		motor[Scissor] = -100;

  	}


    if(joy2Btn(4)== 1 && TSreadState(upTouch) != true){
    	motor[Scissor] = 100;
    	allDown = false;
    }else if (joy2Btn(2)== 1 && TSreadState(downTouch) != true){
    	motor[Scissor] = -100;
    	allUp = false;
    }else {
    	if (allUp==false && allDown==false){
    		motor[Scissor] = 0;
    	}
   }


  //Ramp flipper - button 5 on both joysticks to go up.  button 6 on joy 2 to go down.

}
}
