#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorG,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorH,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
/* typedef struct {
	int x;
	int y;
} XYVal;

XYVal getJoystickXY()
{
	XYVal joy;
	getJoystickSettings(joystick);
	joy.x = joystick.joy1_x2;
	joy.y = joystick.joy1_y2;

}
*/
task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		motor[motorE] = (int)(0.78 * (float)joystick.joy1_x2);
		motor[motorF] = (int)(0.78 * (float)joystick.joy1_y2);
		motor[motorG] = (int)(0.78 * (float)joystick.joy1_x2);
		motor[motorH] = (int)(0.78 * (float)joystick.joy1_y2);
	}

}
