#pragma config(Sensor, S4,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait10Msec(100);
	while(true)
	{
		nxtDisplayCenteredTextLine(4, "Sensor Value: %d", SensorValue[lightSensor]);
	}

}
