#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     colorSensor,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed =40;

task main()
{

	while(true)
	{
		nxtDisplayCenteredTextLine(3, "Sensor Value: %d", SensorValue[sensorLightActive]);

		if (SensorValue[sensorLightActive] > 30)
		{
			motor[motorLeft] = .2 * speed;
			motor[motorRight] = 1 * speed;
			wait1Msec(1);
		}
		else
		{
			motor[motorLeft] = 1 * speed;
			motor[motorRight] = .2 * speed;
		}

	}

}
