#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     USsensor,       sensorSONAR)
#pragma config(Sensor, S4,     lightSensor,    sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BLUETAPE 35

void turnLeft(float rate ,int speed = 100){
	if (speed > 100)
		speed = 100;

	if (rate > 1)
		rate = 1;

	motor[motorLeft] = speed - speed*rate;
	motor[motorRight] = speed;

}

void turnRight(float rate,int speed = 100){
	if (speed > 100)
		speed = 100;

	if (rate > 1)
		rate = 1;

	motor[motorLeft] = speed;
	motor[motorRight] = speed - speed*rate;

}

void foward(int speed = 100)
{
	motor[motorLeft] = speed;
	motor[motorRight] = speed;
}



bool followWall(int sensorName = USsensor, int maintain, int tooFar)
{
		int distance = SensorValue[sensorName];
		nxtDisplayCenteredTextLine(4, "Sensor Value: %d", SensorValue[sensorName]);


		if(distance < maintain)
		{
			nxtDisplayCenteredTextLine(3, "TURN RIGHT");
			turnRight(0.4, 80);
		}
		else if(distance >= tooFar )
		{
			// We've reached the end of the wall
			return true;
		}
		else if(distance >= maintain)
		{
			nxtDisplayCenteredTextLine(3, "TURN LEFT");
			turnLeft(0.4,80);
		}

		return false;
}

bool findLine(int threshold, int direction, float rate = 0.4, int speed = 20)
{
		if(direction < -1)
			direction = -1;
		if(direction > 1)
			direction = 1;
/*
-1 is Left
1 is right
*/
		if(direction == -1)
		{
			turnLeft(rate, speed);

		}

		else if(direction == 1)
		{
			turnRight(rate, speed);

		}
		if( SensorValue[USsensor] > threshold)
			return true;
		else return false;
}






task main()
{
	while(SensorValue[USsensor] >= 40)
	{
		foward(60);
	}
	while(!followWall(USsensor, 30, 255)){wait1Msec(10);}
	while(!findLine( BLUETAPE , 1, 0.4, 20)){wait1Msec(10);}
}
