#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     sensorRight,    sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sensorLeft,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)  // infinite loop:
{
  nxtDisplayCenteredTextLine(3, "Sensor Value: %d", SensorValue[sensorRight]);  // display "Sensor Value: ##"
  nxtDisplayCenteredTextLine(4, "Sensor Value: %d", SensorValue[sensorLeft]);
  wait1Msec(100);  // Wait 100 milliseconds to help display correctly
}



}
